import psycopg2
import os
from pathlib import Path
from dotenv import load_dotenv


connection = None
cursor = None

BASE_DIR = Path(__file__).resolve().parents[2]
ENV_PATH = BASE_DIR / ".env"

load_dotenv(ENV_PATH)


create_table_query = """
DROP TABLE IF EXISTS py_students_transaction;

CREATE TABLE py_students_transaction (
    student_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name TEXT NOT NULL,
    age INTEGER CHECK (age > 0),
    city TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
"""

insert_query = """
INSERT INTO py_students_transaction (full_name, age, city)
VALUES (%s, %s, %s);
"""

select_query = """
SELECT
    student_id,
    full_name,
    age,
    city,
    created_at
FROM py_students_transaction
ORDER BY student_id;
"""

check_count_query = """
SELECT COUNT (*) FROM py_students_transaction;
"""


try:
    connection = psycopg2.connect(
        dbname=os.getenv("DB_NAME"),
        user=os.getenv("DB_USER"),
        password=os.getenv("DB_PASSWORD"),
        host=os.getenv("DB_HOST"),
        port=os.getenv("DB_PORT")
    )

    cursor = connection.cursor()

    cursor.execute(create_table_query)
    connection.commit()
    print("Table created.")

    try:
        cursor.execute(insert_query, ('Anna Smirnova', 25, 'Moscow'))
        cursor.execute(insert_query, ('Bad Student', -5, 'Kazan'))
        cursor.execute(insert_query, ('Pavel Orlov', 29, 'Kazan'))

        connection.commit()

        cursor.execute(select_query)
        rows = cursor.fetchall()

        for row in rows:
            print(row)

    except Exception as error:
        connection.rollback()
        print("Error during transaction:")
        print(error)
        print("Transaction rolled back.")

    cursor.execute(check_count_query)
    result = cursor.fetchone()
    print("Rows in table:", result[0])


except Exception as error:
    print("Database connection error:")
    print(error)

finally:
    if cursor is not None:
        cursor.close()

    if connection is not None:
        connection.close()