import os
import csv
from pathlib import Path

import psycopg2
from dotenv import load_dotenv


connection = None
cursor = None

BASE_DIR = Path(__file__).resolve().parents[2]
ENV_PATH = BASE_DIR / ".env"

load_dotenv(ENV_PATH)

create_table_query = """
DROP TABLE IF EXISTS py_students_csv;

CREATE TABLE py_students_csv (
    student_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name TEXT NOT NULL,
    age INTEGER CHECK (age > 0),
    city TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
"""

insert_query = """
INSERT INTO py_students_csv (full_name, age, city)
VALUES (%s, %s, %s);
"""

select_query = """
SELECT
    student_id,
    full_name,
    age,
    city,
    created_at
FROM py_students_csv
ORDER BY student_id;
"""

check_count_query = """
SELECT COUNT (*) FROM py_students_csv;
"""


try:
    connection = psycopg2.connect(
        dbname=os.getenv("DB_NAME"),
        user=os.getenv("DB_USER"),
        password=os.getenv("DB_PASSWORD"),
        host=os.getenv("DB_HOST"),
        port=os.getenv("DB_PORT")
    )

    cursor = connection.cursor()

    cursor.execute(create_table_query)
    connection.commit()
    print("Table created.")

    project_root = Path(__file__).resolve().parents[1]
    csv_file_path = project_root / "data" / "students.csv"

    students = []

    with open(csv_file_path, newline="", encoding="utf-8") as csvfile:
        reader = csv.DictReader(csvfile)

        for row in reader:
            students.append((
                row["full_name"],
                int(row["age"]),
                row["city"]
            ))
        
        print(f"CSV data loaded. Lines: {len(students)}")
    

    try:
        cursor.executemany(insert_query, students)
        connection.commit()

        cursor.execute(check_count_query)
        result = cursor.fetchone()
        print("Rows inserted:", result[0])

        cursor.execute(select_query)
        rows = cursor.fetchall()

        for row in rows:
            print(row)

    except Exception as error:
        connection.rollback()
        print("Error during transaction:")
        print(error)
        print("Transaction rolled back.")

except Exception as error:
    print("Database error:")
    print(error)

finally:
    if cursor is not None:
        cursor.close()

    if connection is not None:
        connection.close()