import os
import csv
from pathlib import Path

import psycopg2
from dotenv import load_dotenv


connection = None
cursor = None

BASE_DIR = Path(__file__).resolve().parents[2]
ENV_PATH = BASE_DIR / ".env"

load_dotenv(ENV_PATH)

create_load_log_query = """
DROP TABLE IF EXISTS py_load_logs;

CREATE TABLE py_load_logs (
    load_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_file TEXT NOT NULL,
    total_raw_rows INTEGER NOT NULL,
    valid_rows INTEGER NOT NULL,
    rejected_rows INTEGER NOT NULL,
    loaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
"""

create_valid_students_table_query = """
DROP TABLE IF EXISTS py_clean_students;

CREATE TABLE py_clean_students (
    student_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name TEXT NOT NULL,
    age INTEGER CHECK (age > 0),
    city TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
"""

create_rejected_students_table_query = """
DROP TABLE IF EXISTS py_rejected_students;

CREATE TABLE py_rejected_students (
    rejected_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name TEXT,
    age TEXT,
    city TEXT,
    reject_reason TEXT
);
"""

insert_load_logs_query = """
INSERT INTO py_load_logs (
    source_file,
    total_raw_rows,
    valid_rows,
    rejected_rows
)
VALUES (%s, %s, %s, %s);
"""

insert_valid_query = """
INSERT INTO py_clean_students (full_name, age, city)
VALUES (%s, %s, %s);
"""

insert_rejected_query = """
INSERT INTO py_rejected_students (full_name, age, city, reject_reason)
VALUES (%s, %s, %s, %s);
"""

select_load_logs_query = """
SELECT
    load_id,
    source_file,
    total_raw_rows,
    valid_rows,
    rejected_rows,
    loaded_at
FROM py_load_logs
ORDER BY load_id;
"""

select_valid_query = """
SELECT
    student_id,
    full_name,
    age,
    city,
    created_at
FROM py_clean_students
ORDER BY student_id;
"""

select_rejected_query = """
SELECT
    rejected_id,
    full_name,
    age,
    city,
    reject_reason
FROM py_rejected_students
ORDER BY rejected_id;
"""

check_valid_count_query = """
SELECT COUNT (*) FROM py_clean_students;
"""

check_rejected_count_query = """
SELECT COUNT (*) FROM py_rejected_students;
"""


try:
    connection = psycopg2.connect(
        dbname=os.getenv("DB_NAME"),
        user=os.getenv("DB_USER"),
        password=os.getenv("DB_PASSWORD"),
        host=os.getenv("DB_HOST"),
        port=os.getenv("DB_PORT")
    )

    cursor = connection.cursor()

    cursor.execute(create_valid_students_table_query)
    cursor.execute(create_rejected_students_table_query)
    cursor.execute(create_load_log_query)
    connection.commit()
    print("Tables created.")

    project_root = Path(__file__).resolve().parents[1]
    csv_file_path = project_root / "data" / "raw_students.csv"

    valid_students = []
    rejected_students = []

    with open(csv_file_path, newline="", encoding="utf-8") as csvfile:
        reader = csv.DictReader(csvfile)

        for row in reader:
            full_name = row.get("full_name", "").strip()
            age_raw = row.get("age", "").strip()
            city = row.get("city", "").strip()

            if not full_name or not age_raw or not city:
                rejected_students.append((
                    full_name,
                    age_raw,
                    city,
                    "missing required field"
                ))
                continue

            try:
                age = int(age_raw)

                if age <= 0:
                    rejected_students.append((
                        full_name,
                        age_raw,
                        city,
                        "invalid age"
                    ))
                    continue

            except ValueError:
                rejected_students.append((
                    full_name,
                    age_raw,
                    city,
                    "invalid age"
                ))
                continue

            valid_students.append((
                full_name,
                age,
                city
            ))

    print("Valid rows:", len(valid_students))
    print("Rejected rows:", len(rejected_students))    

    try:
        cursor.executemany(insert_valid_query, valid_students)
        cursor.executemany(insert_rejected_query, rejected_students)

        total_raw_rows = len(valid_students) + len(rejected_students)
        cursor.execute(insert_load_logs_query, (
            "raw_students.csv",
            total_raw_rows,
            len(valid_students),
            len(rejected_students)
        ))

        connection.commit()
        print("ETL load completed.")

        cursor.execute(select_load_logs_query)
        logs = cursor.fetchall()

        for log in logs:
            print(log)

    except Exception as error:
        connection.rollback()
        print("Error during ETL load:")
        print(error)
        print("Transaction rolled back.")

except Exception as error:
    print("Database error:")
    print(error)

finally:
    if cursor is not None:
        cursor.close()

    if connection is not None:
        connection.close()