import os
import csv
from pathlib import Path

import psycopg2
from dotenv import load_dotenv


BASE_DIR = Path(__file__).resolve().parents[2]
ENV_PATH = BASE_DIR / ".env"

load_dotenv(ENV_PATH)


def get_connection():
    return psycopg2.connect(
        dbname=os.getenv("DB_NAME"),
        user=os.getenv("DB_USER"),
        password=os.getenv("DB_PASSWORD"),
        host=os.getenv("DB_HOST"),
        port=os.getenv("DB_PORT")
    )


def create_tables(cursor):
    create_load_log_query = """
        DROP TABLE IF EXISTS py_load_logs;

        CREATE TABLE py_load_logs (
            load_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            source_file TEXT NOT NULL,
            total_raw_rows INTEGER NOT NULL,
            valid_rows INTEGER NOT NULL,
            rejected_rows INTEGER NOT NULL,
            loaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        );
    """

    create_clean_students_table_query = """
        DROP TABLE IF EXISTS py_clean_students;

        CREATE TABLE py_clean_students (
            student_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            full_name TEXT NOT NULL,
            age INTEGER CHECK (age > 0),
            city TEXT NOT NULL,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        );
    """

    create_rejected_students_table_query = """
        DROP TABLE IF EXISTS py_rejected_students;

        CREATE TABLE py_rejected_students (
            rejected_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            full_name TEXT,
            age TEXT,
            city TEXT,
            reject_reason TEXT
        );
    """

    cursor.execute(create_load_log_query)
    cursor.execute(create_clean_students_table_query)
    cursor.execute(create_rejected_students_table_query)

    print("Tables created.")


def read_and_validate_csv(csv_file_path):
    clean_students = []
    rejected_students = []

    with open(csv_file_path, newline="", encoding="utf-8") as csvfile:
        reader = csv.DictReader(csvfile)

        for row in reader:
            full_name = row.get("full_name", "").strip()
            age_raw = row.get("age", "").strip()
            city = row.get("city", "").strip()

            if not full_name or not age_raw or not city:
                rejected_students.append((
                    full_name,
                    age_raw,
                    city,
                    "missing required field"
                ))
                continue

            try:
                age = int(age_raw)

                if age <= 0:
                    rejected_students.append((
                        full_name,
                        age_raw,
                        city,
                        "invalid age"
                    ))
                    continue

            except ValueError:
                rejected_students.append((
                    full_name,
                    age_raw,
                    city,
                    "invalid age"
                ))
                continue

            clean_students.append((
                full_name,
                age,
                city
            ))

    print("Valid rows:", len(clean_students))
    print("Rejected rows:", len(rejected_students))

    return clean_students, rejected_students


def load_data(cursor, clean_students, rejected_students, source_file):
    insert_load_logs_query = """
        INSERT INTO py_load_logs (
            source_file,
            total_raw_rows,
            valid_rows,
            rejected_rows
        )
        VALUES (%s, %s, %s, %s);
    """

    insert_clean_query = """
        INSERT INTO py_clean_students (full_name, age, city)
        VALUES (%s, %s, %s);
    """

    insert_rejected_query = """
        INSERT INTO py_rejected_students (full_name, age, city, reject_reason)
        VALUES (%s, %s, %s, %s);
    """

    cursor.executemany(insert_clean_query, clean_students)
    cursor.executemany(insert_rejected_query, rejected_students)

    total_raw_rows = len(clean_students) + len(rejected_students)
    cursor.execute(insert_load_logs_query, (
        source_file,
        total_raw_rows,
        len(clean_students),
        len(rejected_students)
    ))

    print("ETL load completed.")


def print_load_logs(cursor):
    select_load_logs_query = """
        SELECT
            load_id,
            source_file,
            total_raw_rows,
            valid_rows,
            rejected_rows,
            loaded_at
        FROM py_load_logs
        ORDER BY load_id;
    """

    cursor.execute(select_load_logs_query)
    logs = cursor.fetchall()

    for log in logs:
        print(log)


def main():
    connection = None
    cursor = None

    try:
        connection = get_connection()
        cursor = connection.cursor()
        
        create_tables(cursor)
        connection.commit()

        project_root = Path(__file__).resolve().parents[1]
        csv_file_path = project_root / "data" / "raw_students.csv"
        
        clean_students, rejected_students = read_and_validate_csv(csv_file_path)

        try:
            load_data(
                cursor, 
                clean_students, 
                rejected_students, 
                "raw_students.csv"
            )
            connection.commit()

            print_load_logs(cursor)

        except Exception as error:
            connection.rollback()

            print("Error during ETL load:")
            print(error)
            print("Transaction rolled back.")

    except Exception as error:
        print("Database error:")
        print(error)

    finally:
        if cursor is not None:
            cursor.close()

        if connection is not None:
            connection.close()


if __name__ == "__main__":
    main()