DROP TABLE IF EXISTS test_students;

CREATE TABLE test_students (
    student_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(100) NOT NULL,
    age INTEGER CHECK (age > 0),
    city VARCHAR(50) DEFAULT 'Unknown',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO test_students (full_name, age, city)
VALUES ('Maria Ivanova', 22, 'Moscow')
RETURNING *;

INSERT INTO test_students (full_name, age)
VALUES ('Oleg Sidorov', 25)
RETURNING *;

SELECT * FROM test_students;

INSERT INTO test_students (full_name, age, city)
VALUES
    ('Bad Age Test', -5, 'Kazan');

SELECT * FROM test_students;

INSERT INTO test_students (full_name, age, city)
VALUES ('Sergey Orlov', 30, 'Samara')
RETURNING *;