DROP TABLE IF EXISTS import_students;

CREATE TABLE import_students (
    student_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(100) NOT NULL,
    age INTEGER CHECK (age > 0),
    city VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

\copy import_students(full_name, age, city) FROM 'data/new_students.csv' WITH (FORMAT csv, HEADER true);

SELECT * FROM import_students;

SELECT COUNT(*) AS total_rows
FROM import_students;

SELECT *
FROM import_students
WHERE age <= 0;

SELECT *
FROM import_students
WHERE full_name IS NULL
   OR city IS NULL;

SELECT city, COUNT(*) AS students_count
FROM import_students
GROUP BY city
ORDER BY students_count DESC;