DROP TABLE IF EXISTS stg_students ;

CREATE TABLE stg_students (
    full_name TEXT,
    age TEXT,
    city TEXT
);

\copy stg_students(full_name, age, city) FROM 'data/raw_students.csv' WITH (FORMAT csv, HEADER true);

SELECT * FROM stg_students;

SELECT *
FROM stg_students
WHERE age !~ '^[0-9]+$';

SELECT *
FROM stg_students
WHERE age ~ '^[0-9]+$'
  AND age::INTEGER <= 0;

SELECT *
FROM stg_students
WHERE full_name IS NULL
   OR TRIM(full_name) = ''
   OR city IS NULL
   OR TRIM(city) = '';

DROP TABLE IF EXISTS clean_students;

CREATE TABLE clean_students (
    student_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name TEXT NOT NULL,
    age INTEGER NOT NULL CHECK (age > 0),
    city TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO clean_students (full_name, age, city)
SELECT
    TRIM(full_name) AS full_name,
    age::INTEGER AS age,
    TRIM(city) AS city
FROM stg_students
WHERE age ~ '^[0-9]+$'
  AND age::INTEGER > 0
  AND full_name IS NOT NULL
  AND TRIM(full_name) <> ''
  AND city IS NOT NULL
  AND TRIM(city) <> '';

SELECT * FROM clean_students;

DROP TABLE IF EXISTS rejected_students;

CREATE TABLE rejected_students (
    full_name TEXT,
    age TEXT,
    city TEXT,
    reject_reason TEXT,
    rejected_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO rejected_students (full_name, age, city, reject_reason)
SELECT
    full_name,
    age,
    city,
    'invalid age'
FROM stg_students
WHERE age !~ '^[0-9]+$'
   OR (
        age ~ '^[0-9]+$'
        AND age::INTEGER <= 0
   );

INSERT INTO rejected_students (full_name, age, city, reject_reason)
SELECT
    full_name,
    age,
    city,
    'missing required field'
FROM stg_students
WHERE full_name IS NULL
   OR TRIM(full_name) = ''
   OR city IS NULL
   OR TRIM(city) = '';

SELECT * FROM rejected_students;

SELECT
    (SELECT COUNT(*) FROM stg_students) AS total_raw_rows,
    (SELECT COUNT(*) FROM clean_students) AS accepted_rows,
    (SELECT COUNT(*) FROM rejected_students) AS rejected_rows;

SELECT
    reject_reason,
    COUNT(*) AS rejected_count
FROM rejected_students
GROUP BY reject_reason
ORDER BY rejected_count DESC;

SELECT
    ROUND(
        (SELECT COUNT(*) FROM clean_students)::NUMERIC
        / NULLIF((SELECT COUNT(*) FROM stg_students), 0)
        * 100,
        2
    ) AS accepted_percent,
    ROUND(
        (SELECT COUNT(*) FROM rejected_students)::NUMERIC
        / NULLIF((SELECT COUNT(*) FROM stg_students), 0)
        * 100,
        2
    ) AS rejected_percent;

DROP TABLE IF EXISTS load_logs;

CREATE TABLE load_logs (
    load_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_file TEXT NOT NULL,
    total_raw_rows INTEGER NOT NULL,
    accepted_rows INTEGER NOT NULL,
    rejected_rows INTEGER NOT NULL,
    accepted_percent NUMERIC(5, 2),
    rejected_percent NUMERIC(5, 2),
    loaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO load_logs (
    source_file,
    total_raw_rows,
    accepted_rows,
    rejected_rows,
    accepted_percent,
    rejected_percent
)
SELECT
    'data/raw_students.csv' AS source_file,
    (SELECT COUNT(*) FROM stg_students) AS total_raw_rows,
    (SELECT COUNT(*) FROM clean_students) AS accepted_rows,
    (SELECT COUNT(*) FROM rejected_students) AS rejected_rows,
    ROUND(
        (SELECT COUNT(*) FROM clean_students)::NUMERIC
        / NULLIF((SELECT COUNT(*) FROM stg_students), 0)
        * 100,
        2
    ) AS accepted_percent,
    ROUND(
        (SELECT COUNT(*) FROM rejected_students)::NUMERIC
        / NULLIF((SELECT COUNT(*) FROM stg_students), 0)
        * 100,
        2
    ) AS rejected_percent;

SELECT * FROM load_logs;