DROP TABLE IF EXISTS enrollments;
DROP TABLE IF EXISTS students;
DROP TABLE IF EXISTS courses;

CREATE TABLE students (
    student_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(100) NOT NULL,
    age INTEGER CHECK (age > 0),
    city VARCHAR(50) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE courses (
    course_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_name VARCHAR(100) NOT NULL,
    category VARCHAR(50),
    price INTEGER CHECK (price >= 0)
);

CREATE TABLE enrollments (
    enrollment_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id INTEGER NOT NULL,
    course_id INTEGER NOT NULL,
    enrollment_date DATE NOT NULL DEFAULT CURRENT_DATE,
    status VARCHAR(50),
    FOREIGN KEY (student_id) REFERENCES students(student_id),
    FOREIGN KEY (course_id) REFERENCES courses(course_id),
    UNIQUE (student_id, course_id)
);

SELECT * FROM students;
SELECT * FROM courses;
SELECT * FROM enrollments;

INSERT INTO students (full_name, age, city)
VALUES 
    ('Ivan Petrov', 21, 'Moscow'),
    ('Ivan Sidorov', 23, 'Rybinsk'),
    ('Ivan Ivanov', 22, 'Norilsk')
RETURNING *;

INSERT INTO courses (course_name, category, price)
VALUES 
    ('Python for data', 'Python', 12000),
    ('SQL basic', 'SQL', 14000),
    ('Data analysis', 'Analysis', 10500)
RETURNING *;

INSERT INTO enrollments (student_id, course_id)
VALUES (1, 1), (1, 2), (2, 1)
RETURNING *;

SELECT 
    s.full_name,
    s.city,
    c.course_name,
    c.category,
    c.price,
    e.enrollment_date,
    e.status
FROM enrollments e
JOIN students s ON e.student_id = s.student_id
JOIN courses c ON e.course_id = c.course_id
ORDER BY s.full_name, c.course_name;

SELECT 
    c.course_name,
    c.category,
    c.price,
    COUNT (e.enrollment_id) AS students_count
FROM courses c
LEFT JOIN enrollments e 
    ON c.course_id = e.course_id
GROUP BY c.course_name, c.category, c.price
ORDER BY students_count DESC;

SELECT
    s.full_name,
    s.city,
    COUNT (e.enrollment_id) AS courses_count
FROM students s LEFT JOIN enrollments e
    ON s.student_id = e.student_id
GROUP BY s.student_id, s.full_name, s.city
ORDER BY courses_count DESC;

SELECT
    s.student_id,
    s.full_name,
    s.city
FROM students s LEFT JOIN enrollments e
    ON s.student_id = e.student_id
WHERE e.student_id IS NULL;

SELECT
    c.course_id,
    c.course_name,
    c.category,
    c.price
FROM courses c LEFT JOIN enrollments e 
    ON c.course_id = e.course_id
WHERE e.course_id IS NULL;

SELECT
    s.full_name,
    s.city,
    COALESCE (SUM (c.price), 0) AS total_price
FROM students s 
    LEFT JOIN enrollments e ON s.student_id = e.student_id
    LEFT JOIN courses c ON e.course_id = c.course_id
GROUP BY s.student_id, s.full_name, s.city
ORDER BY total_price DESC;

SELECT
    s.full_name,
    s.city,
    COALESCE (MAX (c.price), 0) AS max_course_price
FROM students s
    LEFT JOIN enrollments e ON s.student_id = e.student_id
    LEFT JOIN courses c ON e.course_id = c.course_id
GROUP BY s.student_id, s.full_name, s.city
ORDER BY max_course_price DESC;

SELECT
    s.full_name,
    s.city,
    ROUND (
        COALESCE (AVG (c.price), 0), 2
    ) AS avg_course_price
FROM students s
    LEFT JOIN enrollments e ON s.student_id = e.student_id
    LEFT JOIN courses c ON e.course_id = c.course_id
GROUP BY s.student_id, s.full_name, s.city
ORDER BY avg_course_price DESC;

SELECT
    s.full_name,
    s.city,
    COUNT (e.enrollment_id) AS courses_count,
    SUM (c.price) AS total_price
FROM students s
    JOIN enrollments e ON s.student_id = e.student_id
    JOIN courses c ON e.course_id = c.course_id
GROUP BY s.student_id, s.full_name, s.city
ORDER BY total_price DESC;

SELECT
    s.full_name,
    s.city,
    COUNT (e.enrollment_id) AS courses_count,
    SUM (c.price) AS total_price
FROM students s
    JOIN enrollments e ON s.student_id = e.student_id
    JOIN courses c ON e.course_id = c.course_id
GROUP BY s.student_id, s.full_name, s.city
HAVING SUM (c.price) > 15000
ORDER BY total_price DESC;

SELECT
    c.course_name, 
    c.category,
    COUNT (e.enrollment_id) AS students_count
FROM courses c JOIN enrollments e
    ON c.course_id = e.course_id
GROUP BY c.course_id, c.course_name, c.category
HAVING COUNT (e.enrollment_id) > 1
ORDER BY students_count DESC;

SELECT
    c.course_name, 
    c.category,
    COUNT (e.enrollment_id) AS students_count
FROM courses c LEFT JOIN enrollments e
    ON c.course_id = e.course_id
GROUP BY c.course_id, c.course_name, c.category
HAVING COUNT (e.enrollment_id) < 2
ORDER BY students_count DESC;

SELECT
    c.course_name, 
    c.category,
    COUNT (e.enrollment_id) AS students_count
FROM courses c JOIN enrollments e
    ON c.course_id = e.course_id
GROUP BY c.course_id, c.course_name, c.category
ORDER BY students_count DESC
LIMIT 1;

WITH course_ranks AS (
    SELECT
        c.course_name AS course_name, 
        c.category AS category,
        COUNT (e.enrollment_id) AS students_count,
        RANK() OVER (ORDER BY (COUNT (e.enrollment_id)) DESC) AS course_rank
    FROM courses c JOIN enrollments e
        ON c.course_id = e.course_id
    GROUP BY c.course_id, c.course_name, c.category
)
SELECT
    course_name,
    category,
    students_count
FROM course_ranks
WHERE course_rank = 1;

INSERT INTO enrollments (student_id, course_id)
VALUES (2, 2);

WITH course_ranks AS (
    SELECT
        c.course_name AS course_name, 
        c.category AS category,
        COUNT (e.enrollment_id) AS students_count,
        RANK() OVER (ORDER BY (COUNT (e.enrollment_id)) DESC) AS course_rank
    FROM courses c JOIN enrollments e
        ON c.course_id = e.course_id
    GROUP BY c.course_id, c.course_name, c.category
)
SELECT
    course_name,
    category,
    students_count
FROM course_ranks
WHERE course_rank = 1;

INSERT INTO enrollments (student_id, course_id)
VALUES (1, 3)
RETURNING *;

WITH course_students AS (
    SELECT
        c.course_name AS course_name, 
        c.category AS category,
        COUNT (e.enrollment_id) AS students_count
    FROM courses c LEFT JOIN enrollments e
        ON c.course_id = e.course_id
    GROUP BY c.course_id, c.course_name, c.category
)
SELECT
    course_name,
    category,
    students_count,
    RANK() OVER (ORDER BY students_count DESC) AS rank_value,
    DENSE_RANK() OVER (ORDER BY students_count DESC) AS dense_rank_value,
    ROW_NUMBER() OVER (ORDER BY students_count DESC, course_name) AS row_number_value
FROM course_students
ORDER BY students_count DESC, course_name;






